### ISSUE TITLE
embedded structs don't get serialized

### ISSUE THREAD

**Issue by fvbock** [glycerine/bambam#8] opened 2015-02-19 04:19 UTC
hi,

the readme states that *Structs that contain structs are supported.* but it does not seem to work for me. i just started using go-capnproto/bambam so i think i am just doing something wrong...

i have a main that just `Save()`s and `Load()`s a struct instance. the struct is define in a separate package like this:

```
type Dude struct {
	Name    string   `capid:"0"`
	Age     int      `capid:"1"`
	Address *Address `capid:"2"`
}

type Address struct {
	Street string `capid:"0"`
	Zip    string `capid:"1"`
}
```

the `translateCapn.go` Load and Save methods dont handle the Address - (Pointer or not, also tried annonymous embedded struct). 

i invoced bambam liked this

```
bambam -o capout/ -p dude dude.go
``` 

in the subdrectory. the Load() method will actually have
```
z := dude.ReadRootAddressCapn(capMsg)
```

which does not work - because i am in the Package... removing the package name it works, compiles, but i have the above described problem. this part here makes me think i am just doing something else wrong...

i can make an example repo if that helps.

thx.

**Comment by glycerine** [comment] 2015-02-19 19:52
hi Florian, Thanks for reporting this. I can reproduce it, but the problem isn't immediately obvious. I'll take a closer look tonight. - Jason

**Comment by fvbock** [comment] 2015-02-20 03:05
i patched the struct thing in a dev version. []T worked btw. 

https://github.com/fvbock/bambam/commit/7cc68f2d38b3e8baa3aea0266f5cdaf30c217ca6

i have no idea whether i am using the `x.goType2capTypeCache` anywhere close to what it is intended for and did only very little testing... maybe you can have a brief look. if it looks like i dont do anything completely stupid i will clean up the debug stuff and make a PR.

the module thing remains and i dont really understand the logic there yet.

**Comment by glycerine** [comment] 2015-02-20 09:00
Thanks. It wasn't quite right, but with a small tweak I think it's working. See the latest; 6700c21ec0ed3c83e3e326e9dee52294822a1b5e

Re modules, I'm not sure what the problem is, could you elaborate?  Please run "go test -v" and then look in the testdir* directory to see how the files are put together.

**Comment by fvbock** [comment] 2015-02-20 09:20
ok cool.

modules:
when i call

```
bambam -o capout/ -p <module_name> somefile.go
```

i get the correct `package module_name` header in the files, but the `Load()` function references 

```
z := <module_name>.ReadRootAddressCapn(capMsg)
```

which will then throw

```
translateCapn.go:26: undefined: <module_name>
```

i will run the "go test" stuff on the weekend (i am in JST...) and report back.

**Comment by glycerine** [comment] 2015-02-20 09:42
hmmm not sure I completely follow, but its not uncommon to have to write a
little modification to the generated files to make them fit into your
project. There are alot of possible project arrangements.  You may just
have to change the modules to what you need them to be, using search and
replace in your favorite editor.

On Fri, Feb 20, 2015 at 1:20 AM, Florian von Bock <notifications@github.com>
wrote:

> ok cool.
>
> modules:
> when i call
>
> bambam -o capout/ -p <module_name> somefile.go
>
> i get the correct package module_name header in the files, but the Load()
> function references
>
> z := <module_name>.ReadRootAddressCapn(capMsg)
>
> which will then throw
>
> translateCapn.go:26: undefined: <module_name>
>
> i will run the "go test" stuff on the weekend (i am in JST...) and report
> back.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/glycerine/bambam/issues/8#issuecomment-75209766>.
>



-- 

Best regards,
Jason

--
Jason E. Aten, Ph.D.
j.e.aten@gmail.com
650-429-8602
linkedin: https://www.linkedin.com/pub/jason-e-aten-ph-d/18/313/45a

**Comment by fvbock** [comment] 2015-02-23 02:27
didnt have time to go through the tests :/ i totally agree that some manual tweaking is fine and not to be considered a bug, but here is my reasoning that led me to think that the package thing is a bug: 

when `bambam -p` is set all the function that are generated are defined inside the package, right? or is there a scenario where the `schema.capnp.go` and `translateCapn.go` will be generated with different package headers? 

i think it is a bug if that is not the case (ie. always defined in same package), because then the `ReadRootTYPECapn` func will be defined in the same package scope as the `func (s *TYPE) Load(r io.Reader) error {` functions and then calling the `ReadRoot...` function call will never need the package prefix. or rather should not have - it won't compile.

if the schema and the translate functions could often be in different packages that does not apply...

anyways... that's the reasoning why i thought changing it to never prefix the `ReadRootXXXCapn` functions would be better.

**Comment by glycerine** [comment] 2015-02-23 06:14
Not prefixing the ReadRootXXXCapn functions might be better; at least it
sounds reasonable. I would have to try it; please do and send me a pull
request if it works better for you.

On Sun, Feb 22, 2015 at 6:27 PM, Florian von Bock <notifications@github.com>
wrote:

> didnt have time to go through the tests :/ i totally agree that some
> manual tweaking is fine and not to be considered a bug, but here is my
> reasoning that led me to think that the package thing is a bug:
>
> when bambam -p is set all the function that are generated are defined
> inside the package, right? or is there a scenario where the
> schema.capnp.go and translateCapn.go will be generated with different
> package headers?
>
> i think it is a bug if that is not the case (ie. always defined in same
> package), because then the ReadRootTYPECapn func will be defined in the
> same package scope as the func (s *TYPE) Load(r io.Reader) error {
> functions and then calling the ReadRoot... function call will never need
> the package prefix. or rather should not have - it won't compile.
>
> if the schema and the translate functions could often be in different
> packages that does not apply...
>
> anyways... that's the reasoning why i thought changing it to never prefix
> the ReadRootXXXCapn functions would be better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/glycerine/bambam/issues/8#issuecomment-75481408>.
>



-- 

Best regards,
Jason

--
Jason E. Aten, Ph.D.
j.e.aten@gmail.com
650-429-8602
linkedin: https://www.linkedin.com/pub/jason-e-aten-ph-d/18/313/45a

**Comment by glycerine** [comment] 2015-02-24 03:47
Should be fixed with https://github.com/glycerine/bambam/pull/9
The struct-within-struct Dude and Address test is now a part of the test suite; in rw2.go.txt and rw2_test.go; as of 140307b679524403ca0d14b630f15a4bda05d699

**Closed by glycerine** 2015-02-24 03:47 UTC
